#!/usr/bin/python
import os

destDir = "./objc"

os.system("rm -rf " + destDir)
os.system(
    "j2objc --doc-comments"
    " -use-arc"
    " -sourcepath ./src/main/java/"
    " --prefixes ios_crosscompile_prefixes"
    " -d " + destDir +
    " --strip-reflection $(find src -name *.java)"
)
