//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/qa_wall_logger_client/RemoteLogger.java
//

#ifndef _QA_Wall_RemoteLogger_H_
#define _QA_Wall_RemoteLogger_H_

@protocol QA_Wall_Log;
@protocol QA_Wall_RemoteLogger_Listener;

#include "J2ObjC_header.h"

@interface QA_Wall_RemoteLogger : NSObject {
}

- (instancetype)initWithQA_Wall_RemoteLogger_Listener:(id<QA_Wall_RemoteLogger_Listener>)listener;

- (void)sendWithQA_Wall_Log:(id<QA_Wall_Log>)log;

@end

J2OBJC_EMPTY_STATIC_INIT(QA_Wall_RemoteLogger)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef QA_Wall_RemoteLogger ComQa_wall_logger_clientRemoteLogger;

J2OBJC_TYPE_LITERAL_HEADER(QA_Wall_RemoteLogger)

@protocol QA_Wall_RemoteLogger_Listener < NSObject, JavaObject >

- (NSString *)onGetServerUrl;

- (NSString *)onParseToJsonWithQA_Wall_Log:(id<QA_Wall_Log>)log;

- (void)onSentToNetworkWithNSString:(NSString *)serviceUrl
                       withNSString:(NSString *)parsedObject;

@end

J2OBJC_EMPTY_STATIC_INIT(QA_Wall_RemoteLogger_Listener)

J2OBJC_TYPE_LITERAL_HEADER(QA_Wall_RemoteLogger_Listener)

#endif // _QA_Wall_RemoteLogger_H_
