//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/qa_wall_logger_client/log/Log.java
//

#include "J2ObjC_source.h"
#include "com/qa_wall_logger_client/log/Log.h"
#include "java/util/List.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(QA_Wall_Log)
