//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/qa_wall_logger_client/log/Log.java
//

#ifndef _QA_Wall_Log_H_
#define _QA_Wall_Log_H_

@protocol JavaUtilList;

#include "J2ObjC_header.h"

@protocol QA_Wall_Log < NSObject, JavaObject >

/**
 @return a list of url paths to the service, without any separator;
 */
- (id<JavaUtilList>)getUrlPaths;

@end

J2OBJC_EMPTY_STATIC_INIT(QA_Wall_Log)

#define ComQa_wall_logger_clientLogLog QA_Wall_Log

J2OBJC_TYPE_LITERAL_HEADER(QA_Wall_Log)

#endif // _QA_Wall_Log_H_
