//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/qa_wall_logger_client/log/MessageLog.java
//

#include "J2ObjC_source.h"
#include "com/qa_wall_logger_client/log/MessageLog.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface QA_Wall_MessageLog () {
 @public
  jlong time_;
  NSString *logMsg_;
}
@end

J2OBJC_FIELD_SETTER(QA_Wall_MessageLog, logMsg_, NSString *)

@implementation QA_Wall_MessageLog

- (instancetype)initWithLong:(jlong)time
                withNSString:(NSString *)logMsg {
  if (self = [super init]) {
    self->time_ = time;
    self->logMsg_ = logMsg;
  }
  return self;
}

- (id<JavaUtilList>)getUrlPaths {
  JavaUtilArrayList *path = [[JavaUtilArrayList alloc] init];
  [path addWithId:@"message.php"];
  return path;
}

- (jlong)getTime {
  return time_;
}

- (NSString *)getLogMsg {
  return logMsg_;
}

- (void)copyAllFieldsTo:(QA_Wall_MessageLog *)other {
  [super copyAllFieldsTo:other];
  other->time_ = time_;
  other->logMsg_ = logMsg_;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(QA_Wall_MessageLog)
