//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/qa_wall_logger_client/log/TimeLog.java
//

#include "J2ObjC_source.h"
#include "com/qa_wall_logger_client/log/TimeLog.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface QA_Wall_TimeLog () {
 @public
  NSString *logMsg_;
  jlong timeStart_;
  jlong timeEnd_;
}
@end

J2OBJC_FIELD_SETTER(QA_Wall_TimeLog, logMsg_, NSString *)

@implementation QA_Wall_TimeLog

- (instancetype)initWithNSString:(NSString *)logMsg
                        withLong:(jlong)timeStart
                        withLong:(jlong)timeEnd {
  if (self = [super init]) {
    self->logMsg_ = logMsg;
    self->timeStart_ = timeStart;
    self->timeEnd_ = timeEnd;
  }
  return self;
}

- (id<JavaUtilList>)getUrlPaths {
  JavaUtilArrayList *path = [[JavaUtilArrayList alloc] init];
  [path addWithId:@"time.php"];
  return path;
}

- (NSString *)getLogMsg {
  return logMsg_;
}

- (jlong)getTimeStart {
  return timeStart_;
}

- (jlong)getTimeEnd {
  return timeEnd_;
}

- (void)copyAllFieldsTo:(QA_Wall_TimeLog *)other {
  [super copyAllFieldsTo:other];
  other->logMsg_ = logMsg_;
  other->timeStart_ = timeStart_;
  other->timeEnd_ = timeEnd_;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(QA_Wall_TimeLog)
